FROM arm32v7/ubuntu
LABEL vendor="Bayshore Networks" \
	com.bayshorenetworks.version="1.1" \
	com.bayshorenetworks.version.is-production="yes" \
	com.bayshorenetworks.release-date="2018-03-06"
ENV TERM vt102
ENV HOME /yextend
ARG user=bayshore
ARG uid=1000
ARG gid=1000
RUN apt-get update && apt-get install -y \
		wget \
		make \
		pkg-config \
		zlib1g-dev \
		g++ \
		autoconf \
		libtool \
		zlib1g-dev \
		libssl-dev \
		libbz2-dev \
		libarchive-dev \
		libpcre3-dev \
		uuid-dev \
		poppler-utils \
		python-nose  \
	&& rm -rf /var/lib/apt/lists/*
RUN wget -O /tmp/v3.7.0.tar.gz https://github.com/VirusTotal/yara/archive/v3.7.0.tar.gz && \
	cd /tmp && \
	tar xfz v3.7.0.tar.gz && \
	cd yara-3.7.0 && \
	./bootstrap.sh && \
	./configure --prefix=/usr && \
	make && make install && \
	rm -rf v3.7.0*

ENV YEXTEND_HOME /yextend/
RUN groupadd -g $gid $user && \
	useradd -u $uid -g $gid $user
USER $user
